### PR TITLE
Switch to node-sql-2 for updated Lodash version

### PR DESCRIPTION
**Pull request by recapitalverb**
Since @brianc has abandoned the node-sql repo, I think it is better to use https://github.com/TokyoFarmer/node-sql-2 instead, mainly for the updated Lodash version.

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks for the contribution!

Is this module published on npm anywhere? Does it have significant usage/backing?

With the state of JavaScript security today, I'm reluctant to add a random untrusted GitHub repo as a dependency. 😅

**Comment by recapitalverb** [comment]
If that's the case, you can fork node-sql itself and update Lodash from there since the only reason I used an existing fork of node-sql is Lodash.
You're welcome!

**Comment by nielssj** [comment]
There's an npm package for `node-sql-2` here: https://www.npmjs.com/package/node-sql-2. 
It has plenty of backing, but whether it has significant usage is subjective. After reviewing the minor changes they've committed I've decided to use it in our `keyv-sql` fork.
It would be great to drop the fork, but I understand if you feel it's unsafe. Fact is that `sql` brainc is unmaintained and ridden with vulnerabilities.

**Comment by recapitalverb** [comment]
Closing this PR for being outdated.

**Pull request closed without merging**
